### ISSUE TITLE
LevelUpSDK.h omits LUPassRequestFactory.h

### ISSUE THREAD

**Issue by mharper** [TheLevelUp/levelup-sdk-ios#126]
Using the LevelUpSDK embedded framework and trying to use a `LUPassRequestFactory` in Swift results in:

```
error: use of unresolved identifier 'LUPassRequestFactory'
```

In the bridging header, I already have:

```
#import <LevelUpSDK/LevelUpSDK.h>
```

Adding this to the bridging header solves the problem, but is probably more properly added to `LevelUpSDK.h`:

```
#import <LevelUpSDK/LUPassRequestFactory.h>
```

**Comment by mharper** [comment]
Is this because I'm supposed to use `LUPassRetriever` instead of `LUPassRequestFactory` directly?

**Comment by cwalcott** [comment]
That's correct, we're generally expecting people will use `LUPassRetriever` to get passes.
